// Package goconst provides the runtime types used by code generated by
// protoc-gen-go-const.
//
// Concrete protobuf messages expose every field as a mutable Go field
// or a slice / map header, none of which carries a read-only guarantee
// at the Go type level: callers can assign fields, append / re-slice /
// overwrite repeated entries, or write into / delete from maps.
// protoc-gen-go-const generates, for every message Foo:
//
//   - a Message_Const *struct* type whose sole payload is an unexported
//     *Foo pointer (plus an embedded zero-width [DoNotCompare] marker
//     that makes `view == view` a compile error). Scalar / enum /
//     bytes / excluded-package-message field getters are forwarded
//     verbatim through the struct; repeated
//     and map field getters return the [Slice] / [Slice2] / [Map] /
//     [Map2] read-only collection views defined here.
//   - an AsConst() method on *Foo returning the Message_Const value.
//
// Because Message_Const is a concrete struct with an unexported field
// (not an interface), the classic Go typed-nil footgun disappears: a
// `view == nil` comparison is a compile error rather than a silently-
// wrong check. The corresponding nil-ness question is answered by the
// IsNil() method instead, which reports whether the wrapped pointer is
// nil. Scalar / enum / bytes getters remain nil-safe because the
// protoc-gen-go getters they forward to are themselves nil-safe on a
// nil receiver.
//
// The [Slice] / [Slice2] / [Map] / [Map2] types are concrete struct
// wrappers around the underlying []T / []E / map[K]V / map[K]E, with
// the payload kept in an unexported field. This has two independent
// effects:
//
//   - the Go compiler fully sees the concrete type at call sites, so
//     the range-over-func closures returned by All() are inlined into
//     the caller's stack frame and the loop runs at zero allocation;
//   - the unexported payload cannot be reached without unsafe/reflect,
//     so none of the usual mutation paths compile: s[i] = ...,
//     append(s, ...), copy(s, ...), clear(s), m[k] = ..., delete(m, k).
//     The read-only contract is enforced by Go's type system rather
//     than by convention.
//
// [NewSlice] / [NewMap] are used for scalar element / value types and
// for message types from excluded packages, where elements pass through
// unchanged. [NewSlice2] / [NewMap2] are used for message element /
// value types whose concrete pointer implements [Constable], i.e.
// exposes an AsConst() view; every element is projected through
// AsConst() on access. All four constructors are zero-allocation:
// struct literals whose sole field is the caller's slice / map header,
// so the compiler keeps the value on the stack.
package goconst

import (
	"fmt"
	"iter"
	"maps"
	"slices"
)

// Constable is the constraint satisfied by any value that can be projected
// into a read-only view of type T via its AsConst method. protoc-gen-go-const
// emits an AsConst() <MessageName>_Const method on every generated message
// pointer type, so *FooPb satisfies Constable[FooPb_Const].
type Constable[T any] interface {
	AsConst() T
}

// DoNotCompare is a zero-width, non-comparable marker type intended to
// be carried as a field in a struct to make the whole struct non-
// comparable at compile time. Because [0]func() occupies no memory but
// is itself non-comparable, `a == b` on any struct that carries a
// DoNotCompare field is a compile error, while the struct layout and
// zero value remain otherwise unchanged.
//
// The recommended form is a blank-named field:
//
//	type Foo struct {
//		_ goconst.DoNotCompare
//		// ...other fields...
//	}
//
// Using a blank name (rather than embedding) preserves the non-
// comparability guarantee while making the field unreachable by
// selector: `v.DoNotCompare = ...`, `&v.DoNotCompare`, and
// struct-literal `Foo{DoNotCompare: ...}` all fail to compile, and
// any method ever added to DoNotCompare will not get promoted onto
// Foo. Plain embedding (`goconst.DoNotCompare` without a name) is
// still accepted and semantically equivalent for the non-comparability
// guarantee, but exposes the name and promotes methods, so the
// blank-named form is preferred.
//
// It is carried (in blank-named form) by every collection view type
// defined in this package ([Slice] / [Slice2] / [Map] / [Map2]) and
// by every <Message>_Const wrapper struct produced by
// protoc-gen-go-const, so that pointer-equality reasoning on wrapper
// values — which would be meaningless on a view whose sole semantic
// content is the forwarded-to message — surfaces as a build error
// rather than as a silently-wrong check. Cf.
// https://pkg.go.dev/google.golang.org/protobuf/internal/pragma#DoNotCompare,
// from which this pattern is borrowed.
type DoNotCompare [0]func()

// ---------------------------------------------------------------------------
// Slice — read-only view over a repeated protobuf field.
// ---------------------------------------------------------------------------

// Slice is a read-only view over a repeated protobuf field of element
// type T, for scalar / enum / bytes element types and for message
// element types from --exclude_packages (where elements are kept as
// concrete *T pointers rather than projected through AsConst()).
//
// Slice is a struct with an unexported field, so the usual mutation
// operations fail at compile time:
//
//	s := p.AsConst().ConstTags()
//	s[0] = "x"          // compile error: cannot index
//	s = append(s, "x")  // compile error: first argument to append must be a slice
//	copy(s, tags)       // compile error: first argument to copy must be a slice
//	clear(s)            // compile error: argument must be a map, slice, or …
//
// The type system enforces the read-only contract; no convention or
// runtime check is involved.
//
// Iteration is done via All / Values, which return the stdlib
// range-over-func shapes ([iter.Seq2] / [iter.Seq]) so callers can
// either use the native `for i, v := range s.All()` form or feed
// s.Values() directly into [slices.Collect], [slices.Sorted], or any
// iter.Seq-aware third-party helper (e.g. https://pkg.go.dev/github.com/samber/lo/it).
//
// Slice satisfies [fmt.Stringer]: printing it with fmt.Print / log.Print
// / %v produces exactly the same output as printing the underlying []T
// directly — no extra "Slice[...]" wrapper.
type Slice[T any] struct {
	_ DoNotCompare
	s []T
}

// NewSlice returns a read-only [Slice] view over s. Elements are returned
// as-is from At / All, so it is suitable for scalar element types and for
// message element types whose [Constable] projection is not desired
// (e.g. messages from excluded packages).
func NewSlice[T any](s []T) Slice[T] {
	return Slice[T]{s: s}
}

// Len returns the number of elements in the underlying slice.
func (c Slice[T]) Len() int { return len(c.s) }

// At returns the element at index i. It panics with an out-of-range
// error if i is not in [0, Len()), matching built-in slice semantics.
func (c Slice[T]) At(i int) T { return c.s[i] }

// All returns a range-over-func iterator yielding (index, element)
// pairs in order, compatible with Go 1.23+
// "for i, v := range s.All()". Analogue of [slices.All].
func (c Slice[T]) All() iter.Seq2[int, T] { return slices.All(c.s) }

// Values returns a range-over-func iterator yielding just the elements
// in order. Companion to [Slice.All]; feeds directly into stdlib sinks
// such as [slices.Collect] / [slices.Sorted]. Analogue of [slices.Values].
func (c Slice[T]) Values() iter.Seq[T] { return slices.Values(c.s) }

// IsNil reports whether the underlying slice has no elements to iterate
// over — a nil slice and an empty slice both report true, matching the
// "nothing to read" reading.
func (c Slice[T]) IsNil() bool { return len(c.s) == 0 }

// String prints the underlying []T, so fmt.Print(s) produces exactly
// the same output as fmt.Print([]T(s.s)) would — no "Slice[...]"
// wrapper around the native slice rendering.
func (c Slice[T]) String() string { return fmt.Sprint(c.s) }

// ---------------------------------------------------------------------------
// Slice2 — read-only view over a repeated message field with AsConst projection.
// ---------------------------------------------------------------------------

// Slice2 is a read-only view over a repeated protobuf field of message
// element type *E, projected element-by-element through E.AsConst() to
// yield the read-only view type T. Compared to [Slice], the element
// type seen by callers is the read-only view T (e.g. Address_Const),
// not the concrete pointer *E, so the type system also denies callers
// the ability to mutate the underlying message by dereferencing an
// element pointer.
//
// The extra type parameter E is the element storage type (e.g. *Address)
// and is required so that the per-element AsConst projection can be
// statically dispatched at zero cost. Callers rarely spell it out
// themselves: the generator emits the full signature on *_Const getters
// and Go 1.23+ constraint type inference fills E in at every
// goconst.NewSlice2(...) call site.
//
// Same compile-time read-only contract as [Slice]: the unexported
// payload is unreachable without unsafe/reflect, so s[i] = ..., append,
// copy, and clear all fail to compile.
type Slice2[T any, E Constable[T]] struct {
	_ DoNotCompare
	s []E
}

// NewSlice2 returns a read-only [Slice2] view over s whose elements are
// projected through the [Constable] AsConst method. It is used by the
// generator for repeated message fields whose element type has a _Const
// view.
func NewSlice2[T any, E Constable[T]](s []E) Slice2[T, E] {
	return Slice2[T, E]{s: s}
}

// Len returns the number of elements in the underlying slice.
func (c Slice2[T, E]) Len() int { return len(c.s) }

// At returns the AsConst() projection of the element at index i. It
// panics with an out-of-range error if i is not in [0, Len()), matching
// built-in slice semantics.
func (c Slice2[T, E]) At(i int) T { return c.s[i].AsConst() }

// All returns a range-over-func iterator yielding (index, projected
// element) pairs in order. Each element is projected through AsConst()
// on access, so the yielded value type is T (e.g. Address_Const), not
// the concrete E (e.g. *Address).
func (c Slice2[T, E]) All() iter.Seq2[int, T] {
	return func(yield func(int, T) bool) {
		for i, v := range c.s {
			if !yield(i, v.AsConst()) {
				return
			}
		}
	}
}

// Values returns a range-over-func iterator yielding just the projected
// elements in order. Companion to [Slice2.All].
func (c Slice2[T, E]) Values() iter.Seq[T] {
	return func(yield func(T) bool) {
		for _, v := range c.s {
			if !yield(v.AsConst()) {
				return
			}
		}
	}
}

// IsNil reports whether the underlying slice has no elements to iterate
// over — a nil slice and an empty slice both report true.
func (c Slice2[T, E]) IsNil() bool { return len(c.s) == 0 }

// String prints the underlying []E (i.e. the raw []*Message before
// AsConst projection) so that protobuf messages render via their own
// rich prototext-style String() rather than as opaque addresses.
func (c Slice2[T, E]) String() string { return fmt.Sprint(c.s) }

// ---------------------------------------------------------------------------
// Map — read-only view over a map protobuf field.
// ---------------------------------------------------------------------------

// Map is a read-only view over a map protobuf field with key type K and
// value type V, for scalar / enum / bytes value types and for message
// value types from --exclude_packages.
//
// Same compile-time read-only contract as [Slice]: the unexported
// payload is unreachable without unsafe/reflect, so m[k] = ... and
// delete(m, k) fail to compile. Iteration is done via All / Keys /
// Values, which return the stdlib [maps.All] / [maps.Keys] /
// [maps.Values] shapes.
//
// Map satisfies [fmt.Stringer]: printing it produces exactly the same
// output as printing the underlying map[K]V directly.
type Map[K comparable, V any] struct {
	_ DoNotCompare
	m map[K]V
}

// NewMap returns a read-only [Map] view over m. Values are returned as-is
// from Get / All, so it is suitable for scalar value types and for message
// value types whose [Constable] projection is not desired.
func NewMap[K comparable, V any](m map[K]V) Map[K, V] {
	return Map[K, V]{m: m}
}

// Len returns the number of entries in the underlying map.
func (c Map[K, V]) Len() int { return len(c.m) }

// Get returns the value associated with key k and true if present,
// or the ordinary Go zero value of V and false otherwise — the same
// shape as the comma-ok form of a built-in map lookup.
func (c Map[K, V]) Get(k K) (V, bool) {
	v, ok := c.m[k]
	return v, ok
}

// Has reports whether key k is present in the underlying map.
func (c Map[K, V]) Has(k K) bool {
	_, ok := c.m[k]
	return ok
}

// All returns a range-over-func iterator yielding (key, value) pairs
// in unspecified order, compatible with Go 1.23+
// "for k, v := range m.All()". Analogue of [maps.All].
func (c Map[K, V]) All() iter.Seq2[K, V] { return maps.All(c.m) }

// Keys returns a range-over-func iterator yielding just the keys in
// unspecified order. Analogue of [maps.Keys].
func (c Map[K, V]) Keys() iter.Seq[K] { return maps.Keys(c.m) }

// Values returns a range-over-func iterator yielding just the values
// in unspecified order. Analogue of [maps.Values].
func (c Map[K, V]) Values() iter.Seq[V] { return maps.Values(c.m) }

// IsNil reports whether the underlying map has no entries to iterate
// over — a nil map and an empty map both report true.
func (c Map[K, V]) IsNil() bool { return len(c.m) == 0 }

// String prints the underlying map[K]V, so fmt.Print(m) produces
// exactly the same output as fmt.Print(map[K]V(m.m)) would — no
// "Map[...]" wrapper around the native map rendering.
func (c Map[K, V]) String() string { return fmt.Sprint(c.m) }

// ---------------------------------------------------------------------------
// Map2 — read-only view over a map message-valued field with AsConst projection.
// ---------------------------------------------------------------------------

// Map2 is a read-only view over a map protobuf field with message value
// type *E, projected value-by-value through E.AsConst() to yield the
// read-only view type V (e.g. Address_Const). As with [Slice2], the
// extra type parameter E (e.g. *Address) is required for the
// statically-dispatched per-value projection; callers rarely spell it
// out themselves.
//
// Same compile-time read-only contract as [Map]: the unexported payload
// is unreachable without unsafe/reflect, so m[k] = ... and delete(m, k)
// fail to compile.
type Map2[K comparable, V any, E Constable[V]] struct {
	_ DoNotCompare
	m map[K]E
}

// NewMap2 returns a read-only [Map2] view over m whose values are projected
// through the [Constable] AsConst method. It is used by the generator for
// map fields whose value type has a _Const view.
func NewMap2[K comparable, V any, E Constable[V]](m map[K]E) Map2[K, V, E] {
	return Map2[K, V, E]{m: m}
}

// Len returns the number of entries in the underlying map.
func (c Map2[K, V, E]) Len() int { return len(c.m) }

// Get returns the AsConst() projection of the value associated with
// key k and true if present, or a miss-safe nil-backed view of V and
// false otherwise. The second return value is the *authoritative*
// presence flag; the first is deliberately chosen so that v.GetX() is
// safe to call whether ok is true or false.
//
// On a miss the map lookup yields the Go zero value of E (a nil *Foo
// pointer); AsConst is a pointer-receiver method that merely wraps
// its receiver into a Foo_Const{p: …} struct without dereferencing it,
// so calling it on the nil receiver produces exactly the nil-backed
// view Foo_Const{p: nil} we want — no branch needed.
func (c Map2[K, V, E]) Get(k K) (V, bool) {
	v, ok := c.m[k]
	return v.AsConst(), ok
}

// Has reports whether key k is present in the underlying map.
func (c Map2[K, V, E]) Has(k K) bool {
	_, ok := c.m[k]
	return ok
}

// All returns a range-over-func iterator yielding (key, projected
// value) pairs in unspecified order. Each value is projected through
// AsConst() on access, so the yielded value type is V (e.g.
// Address_Const), not the concrete E (e.g. *Address).
func (c Map2[K, V, E]) All() iter.Seq2[K, V] {
	return func(yield func(K, V) bool) {
		for k, v := range c.m {
			if !yield(k, v.AsConst()) {
				return
			}
		}
	}
}

// Keys returns a range-over-func iterator yielding just the keys in
// unspecified order. Analogue of [maps.Keys].
func (c Map2[K, V, E]) Keys() iter.Seq[K] { return maps.Keys(c.m) }

// Values returns a range-over-func iterator yielding just the
// projected values in unspecified order.
func (c Map2[K, V, E]) Values() iter.Seq[V] {
	return func(yield func(V) bool) {
		for _, v := range c.m {
			if !yield(v.AsConst()) {
				return
			}
		}
	}
}

// IsNil reports whether the underlying map has no entries to iterate
// over — a nil map and an empty map both report true.
func (c Map2[K, V, E]) IsNil() bool { return len(c.m) == 0 }

// String prints the underlying map[K]E (i.e. the raw map[K]*Message
// before AsConst projection) so that protobuf messages render via their
// own rich prototext-style String() rather than as opaque addresses.
func (c Map2[K, V, E]) String() string { return fmt.Sprint(c.m) }
