package main

import (
	"fmt"
	"strings"
	"sync"

	"github.com/spf13/pflag"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "0.1.0"

// protoPackage is the import path of the runtime proto package.
const protoPackage = protogen.GoImportPath("google.golang.org/protobuf/proto")

// goconstPackage is the import path of this repo's runtime helper package,
// which exposes the read-only Slice / Map interfaces and the
// NewSlice / NewSlice2 / NewMap / NewMap2 constructors used by generated
// *_Const views for repeated / map fields.
const goconstPackage = protogen.GoImportPath("github.com/Kybxd/goconst")

func main() {
	var flags pflag.FlagSet
	excludePackages := flags.StringSlice("exclude_packages", nil, "List of Go package import paths to exclude from const interface generation")
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL | pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
		gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
		gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			NewGenerator(gen, f, *excludePackages).Generate()
		}
		return nil
	})
}

type Generator struct {
	gen  *protogen.Plugin
	file *protogen.File

	once    sync.Once
	genFile *protogen.GeneratedFile

	// excludePackages contains the list of Go package import paths that should be excluded
	// from const interface generation. Messages from these packages will not have _Const interfaces.
	excludePackages map[string]bool
}

func NewGenerator(gen *protogen.Plugin, file *protogen.File, excludePackages []string) *Generator {
	// Parse exclude packages from command line flags
	excludePackagesMap := make(map[string]bool)
	if len(excludePackages) > 0 {
		for _, pkg := range excludePackages {
			excludePackagesMap[strings.TrimSpace(pkg)] = true
		}
	}
	return &Generator{
		gen:             gen,
		file:            file,
		excludePackages: excludePackagesMap,
	}
}

// shouldExcludeMessage checks if a message should be excluded from const interface generation
// based on its package import path.
func (x *Generator) shouldExcludeMessage(message *protogen.Message) bool {
	// Check if this message's package is in the exclude list
	pkgPath := string(message.GoIdent.GoImportPath)
	return x.excludePackages[pkgPath]
}

func (x *Generator) Generate() {
	for _, message := range x.file.Messages {
		// Skip messages from excluded packages
		if x.shouldExcludeMessage(message) {
			continue
		}
		x.genMessageConstAPI(message)
	}
}

func (x *Generator) g() *protogen.GeneratedFile {
	x.once.Do(func() {
		filename := x.file.GeneratedFilenamePrefix + ".const.pb.go"
		x.genFile = x.gen.NewGeneratedFile(filename, x.file.GoImportPath)
		x.genFile.P("// Code generated by protoc-gen-go-const. DO NOT EDIT.")
		x.genFile.P("// versions:")
		x.genFile.P("//  protoc-gen-go-const v", version)
		x.genFile.P("//  protoc              ", x.protocVersion())
		if x.file.Proto.GetOptions().GetDeprecated() {
			x.genFile.P("// ", x.file.Desc.Path(), " is a deprecated file.")
		} else {
			x.genFile.P("// source: ", x.file.Desc.Path())
		}
		x.genFile.P()
		x.genFile.P("package ", x.file.GoPackageName)
		x.genFile.P()
	})
	return x.genFile
}

func (x *Generator) protocVersion() string {
	v := x.gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func (x *Generator) genMessageConstAPI(message *protogen.Message) {
	g := x.g()
	msgName := message.GoIdent.GoName

	// _Const interface.
	g.P("// ", msgName, "_Const is a read-only interface of ", msgName, ".")
	g.P("type ", msgName, "_Const interface {")
	// Embed proto.Message so that any Const value is also a proto.Message.
	g.P(protoPackage.Ident("Message"))
	g.P()
	for _, field := range message.Fields {
		g.P("Get", field.GoName, "() ", x.fieldConstType(field))
	}
	g.P("}")
	g.P()

	// Define an unexported wrapper struct that embeds the concrete message, so
	// that it inherits all the Get* methods whose signatures do not change, and
	// then assert at compile time that the wrapper implements the _Const
	// interface.
	g.P("type _", msgName, "_Const struct {")
	g.P("*", msgName)
	g.P("}")
	g.P()
	g.P("var _ ", msgName, "_Const = (*_", msgName, "_Const)(nil)")
	g.P()

	// AsConst returns x as its read-only _Const interface view.
	g.P("// AsConst returns x as its read-only ", msgName, "_Const view.")
	g.P("func (x *", msgName, ") AsConst() ", msgName, "_Const {")
	g.P("return &_", msgName, "_Const{", msgName, ": x}")
	g.P("}")
	g.P()

	// Override Get* methods whose signatures differ between the concrete
	// message and the _Const interface (message / list / map fields).
	for _, field := range message.Fields {
		x.genOverrideGetter(message, field)
	}

	// Recurse into nested messages so that their interfaces are emitted too.
	for _, nested := range message.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		x.genMessageConstAPI(nested)
	}
}

// fieldConstType returns the Go type string used for the given field's Get
// method return type in its _Const interface view.
func (x *Generator) fieldConstType(field *protogen.Field) string {
	g := x.g()
	switch {
	case field.Desc.IsList():
		elem := x.fieldElemConstType(field)
		return fmt.Sprintf("%s[%s]", g.QualifiedGoIdent(goconstPackage.Ident("Slice")), elem)
	case field.Desc.IsMap():
		keyField := field.Message.Fields[0]
		valField := field.Message.Fields[1]
		keyType := x.fieldGoType(keyField)
		valType := x.fieldElemConstType(valField)
		return fmt.Sprintf("%s[%s, %s]", g.QualifiedGoIdent(goconstPackage.Ident("Map")), keyType, valType)
	case field.Desc.Kind() == protoreflect.MessageKind || field.Desc.Kind() == protoreflect.GroupKind:
		return x.messageConstGoType(field.Message)
	default:
		return x.fieldGoType(field)
	}
}

// fieldElemConstType returns the Go type string used for a single element
// (list element or map value). Message elements are returned as their _Const
// interface view; scalar/enum elements are returned as-is.
func (x *Generator) fieldElemConstType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		// If the message type is from an excluded package, return the original type
		if x.shouldExcludeMessage(field.Message) {
			return "*" + x.g().QualifiedGoIdent(field.Message.GoIdent)
		}
		return x.messageConstGoType(field.Message)
	default:
		return x.scalarFieldGoType(field)
	}
}

// messageConstGoType returns the _Const interface Go type string for the
// given message, handling cross-package references via QualifiedGoIdent so
// that the import is added automatically.
func (x *Generator) messageConstGoType(msg *protogen.Message) string {
	g := x.g()

	// If this message is from an excluded package, return the original message type
	if x.shouldExcludeMessage(msg) {
		return "*" + g.QualifiedGoIdent(msg.GoIdent)
	}

	return g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       msg.GoIdent.GoName + "_Const",
		GoImportPath: msg.GoIdent.GoImportPath,
	})
}

// fieldGoType returns the Go type string used for the given field on the
// concrete message, following the same rules as protoc-gen-go.
func (x *Generator) fieldGoType(field *protogen.Field) string {
	g := x.g()
	goType := x.scalarFieldGoType(field)
	if field.Desc.Kind() == protoreflect.MessageKind || field.Desc.Kind() == protoreflect.GroupKind {
		goType = "*" + g.QualifiedGoIdent(field.Message.GoIdent)
	}
	switch {
	case field.Desc.IsList():
		return "[]" + goType
	case field.Desc.IsMap():
		keyType := x.fieldGoType(field.Message.Fields[0])
		valType := x.fieldGoType(field.Message.Fields[1])
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}
	return goType
}

// scalarFieldGoType returns the Go type string for the field ignoring
// list/map modifiers (i.e. the element type for scalars/enums, or the message
// pointer type for messages).
func (x *Generator) scalarFieldGoType(field *protogen.Field) string {
	g := x.g()
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.EnumKind:
		return g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return "*" + g.QualifiedGoIdent(field.Message.GoIdent)
	}
	return ""
}

// genOverrideGetter emits a Get* method on the _<MessageName>_Const wrapper
// whenever its signature differs from the embedded concrete message's getter,
// i.e. for message / list / map fields. List and map fields delegate to the
// runtime constructors goconst.NewSlice / goconst.NewSlice2 / goconst.NewMap
// / goconst.NewMap2; the *2 variants are chosen for element types that
// expose an AsConst() view (see goconst.Constable).
func (x *Generator) genOverrideGetter(message *protogen.Message, field *protogen.Field) {
	g := x.g()
	msgName := message.GoIdent.GoName
	recv := fmt.Sprintf("(x *_%s_Const)", msgName)

	switch {
	case field.Desc.IsList():
		elemConstType := x.fieldElemConstType(field)
		wrapAsConst := x.isMessageElem(field) && !x.shouldExcludeMessage(field.Message)
		retType := fmt.Sprintf("%s[%s]", g.QualifiedGoIdent(goconstPackage.Ident("Slice")), elemConstType)

		g.P("func ", recv, " Get", field.GoName, "() ", retType, " {")
		if wrapAsConst {
			// NewSlice2 needs the projected type T as an explicit type
			// argument because it only appears in the Constable[T]
			// constraint, not in the function's value parameter list.
			g.P("return ", g.QualifiedGoIdent(goconstPackage.Ident("NewSlice2")), "[", elemConstType, "](x.", msgName, ".Get", field.GoName, "())")
		} else {
			g.P("return ", g.QualifiedGoIdent(goconstPackage.Ident("NewSlice")), "(x.", msgName, ".Get", field.GoName, "())")
		}
		g.P("}")
		g.P()

	case field.Desc.IsMap():
		keyField := field.Message.Fields[0]
		valField := field.Message.Fields[1]
		keyType := x.fieldGoType(keyField)
		valConstType := x.fieldElemConstType(valField)
		wrapAsConst := x.isMessageElem(valField) && !x.shouldExcludeMessage(valField.Message)
		retType := fmt.Sprintf("%s[%s, %s]", g.QualifiedGoIdent(goconstPackage.Ident("Map")), keyType, valConstType)

		g.P("func ", recv, " Get", field.GoName, "() ", retType, " {")
		if wrapAsConst {
			// NewMap2 needs [K, V] as explicit type arguments for the
			// same reason as NewSlice2 above.
			g.P("return ", g.QualifiedGoIdent(goconstPackage.Ident("NewMap2")), "[", keyType, ", ", valConstType, "](x.", msgName, ".Get", field.GoName, "())")
		} else {
			g.P("return ", g.QualifiedGoIdent(goconstPackage.Ident("NewMap")), "(x.", msgName, ".Get", field.GoName, "())")
		}
		g.P("}")
		g.P()

	case field.Desc.Kind() == protoreflect.MessageKind || field.Desc.Kind() == protoreflect.GroupKind:
		// Skip override getter for excluded packages.
		if x.shouldExcludeMessage(field.Message) {
			return
		}
		retType := x.messageConstGoType(field.Message)
		g.P("func ", recv, " Get", field.GoName, "() ", retType, " {")
		g.P("return x.", msgName, ".Get", field.GoName, "().AsConst()")
		g.P("}")
		g.P()
	}
}

// isMessageElem reports whether the given field represents a message-kind
// element (i.e. list elements or map values that hold messages).
func (x *Generator) isMessageElem(field *protogen.Field) bool {
	return field.Desc.Kind() == protoreflect.MessageKind || field.Desc.Kind() == protoreflect.GroupKind
}
